0backend: 'sqlite'

sqlite:
  db: '/mnt/bbvolume/server_homes/vitoz/mnt/tmp/scratch/vitoz/Data/Analysis/20200123_testalign/db_2/spherpro_v2.db'



# Cellprofiler output info:
crop_dir: '/mnt/bbvolume/server_homes/vitoz/mnt/tmp/scratch/vitoz/Data/Analysis/20190726_oexp_p165-161-bigoverexpression_v3_a1/crop'
cp_dir: '/mnt/bbvolume/server_homes/vitoz/mnt/tmp/scratch/vitoz/Data/Analysis/20190726_oexp_p165-161-bigoverexpression_v3_a1/cpout'

stack_dir:
  path: '../config/spherpro/stacks'
  id_col: 'index' # Default: 'index'
  name_col: 'mass' # Default: 'name'
  type_col: 'channel_type' # Default: 'channel_type'
  sep: ',' # Default: ','
  stack_col: 'file_name'
  
stack_relations:
  path: '../config/spherpro/stackrelations.csv'
  stack_col: 'Stack' # Default: 'Stack'
  parent_col: 'Parent' # Default: 'Parent'
  modname_col: 'ModificationName' # Default: 'ModificationName'
  modpre_col: 'ModificationPrefix' # Default: 'ModificationPrefix'
  ref_col: 'RefStack' # Default: 'RefStack'
  sep: ',' # Default: ','
  
cpoutput:
  measurement_csv:
    objects: ['cell', 'cyto', 'nucleiexp']
    default_object: 'cell'
  relation_csv:
    path: 'Object relationships.csv'
  images_csv:
    path: 'Image.csv'
    re_meta: '(?P<basename>.*)_l(?P<crop_number>[0-9]*)_x(?P<image_pos_x>[0-9]*)_y(?P<image_pos_y>[0-9]*)_.*'
    ome_meta_regexp: '(?P<slideac_name>.*)_s[0-9]+_p(?P<site_mcd_panoramaid>[0-9]+)_r(?P<acquisition_mcd_roiid>[0-9]+)_a(?P<acquisition_mcd_acid>[0-9]+)_ac.*'
    ome_folder_dirs: [ '/mnt/bbvolume/server_homes/vitoz/mnt/tmp/scratch/vitoz/Data/Analysis/20190726_oexp_p165-161-bigoverexpression_v3_a1/ometiff']
    slide_regexp: '.*_(?P<sampleblock_name>.*)_slide(?P<slide_number>[0-9]+)_.*'
    mask_filename_col_prefix: 'FileName_'
    mask_dir: '{cp_dir}/masks'
    stackimg_dir: '{cp_dir}/imgs'
    
# Experiment layout info:
layout_csv:
  path: '../config/spherpro/plate_layout.csv'
  plate_col: 'plate'
  well_col: 'well'
  condition_col: 'condition'
  control_col: 'iscontrol'
  timepoint_col: 'timepoint'

# Barcode Info:
barcode_csv:
  path: '../config/240_well_barcoding_key.csv'
  well_col: 'well'
  plate_col: 'plate'
  sep: ','

# Pannel Info:
pannel_csv:
  path: '../config/pannel.csv'
  channel_name: 'metal'
  display_name: 'Target'
  ilastik_name: 'ilastik'
  barcode_name: 'sphereseg'
  clone_name: 'Antibody Clone'
  concentration_name: 'Final Concentration / Dilution'
  tube_name: 'Tube Number'
  
