FROM czsip/fiji_linux64_baseimage:1.3.0

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion && \
    apt-get clean

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    /opt/conda/bin/conda clean -afy
RUN conda install -y -c conda-forge mamba
RUN mamba install -y -c conda-forge openjdk=8
RUN mamba install -y -c conda-forge -c bioconda pandas pyimagej python=3.7 scikit-image jupyter jupytext imctools=1.0.7 imglyb=0.3.5 tqdm pip
RUN pip install czifile==2019.7.2 imagecodecs==2019.12.31 imagecodecs-lite==2019.12.3 imagesize==1.2.0 tifffile==2019.7.26.2
RUN python -c "import imagej;imagej.init('/Fiji.app')"
WORKDIR /root

