# Use the official image as a parent image.
FROM continuumio/miniconda3:4.8.2

# Set the working directory.
WORKDIR ~

# Run the command inside your image filesystem.
RUN conda config --set always_yes yes --set changeps1 no
RUN conda install -c conda-forge mamba pip python=3.8
RUN mamba install -c conda-forge -c bioconda pandas numpy tifffile imctools=1.0.7