# Please look at the .schema.yml for documentation of the values
cellprofiler_container: 'docker://cellprofiler/cellprofiler:3.1.8'
input_data_folders:
  - '/mnt/imls-bod/Zoidberg_Data/'
#  - 'resources/zips'
input_file_regexp: '.*20190(5|6|7)[0-9]+_p17(3|6)_slide[0-9]+_ac[0-9]_vz.zip'

csv_panel: config/pannel.csv
csv_panel_metal: 'metal'
csv_panel_ilastik: 'ilastik'
csv_panel_full: 'full'
csv_panel_sphereseg: 'sphereseg'

compensation:
  fns_compensation:
    - '/mnt/imls-bod/Zoidberg_Data/20190618_bc126v1spillover_slide1_ac7_vz.zip'
    - '/mnt/imls-bod/Zoidberg_Data/20190618_overexpressionv7spillover_slide1_ac3_vz.zip'
  fn_ss_panel:
    'resources/compensation_singlestain_panel.csv'