# Please look at the .schema.yml for documentation of the values
input_data_folders:
  - '/mnt/imls-bod/Zoidberg_Data/'
input_file_regexp: '.*20190(5|6|7)[0-9]+_p17(3|6)_slide[0-9]+_ac[0-9]_vz.zip'

csv_panel: config/pannel.csv
csv_panel_metal: 'metal'
csv_panel_ilastik: 'ilastik'
csv_panel_full: 'full'
csv_panel_sphereseg: 'sphereseg'
