$schema: "http://json-schema.org/draft-07/schema#"
description: a configuration for the imc segmentation pipeline
properties:
  input_data_folders:
    type: array
    description: list of input results folders[example_data]
    required: true

  input_file_regexp:
    type: string
    description: regexp pattern that files/folders need to much to be considered to contain input `.mcd` files
    required: true

  output_folder:
    type: string
    default: results
    description: path to output results
    required: false

  cellprofiler_container:
    type: string
    default: 'docker://cellprofiler/cellprofiler:3.1.9'
    description: Default cellprofiler singularity container
    required: fals

  cellprofiler_plugins:
    type: string
    default: ../../cp_plugins/ImcPluginsCP/plugins
    description: path to the default cellprofiler plugins to be used
    required: false

  ilastik_container:
    type: string
    default: 'docker://ilastik/ilastik-from-binary:1.3.3b1'
    description: Default Ilastik singularity container
    required: false

